version: '2'
services:
    node:
      build: './stackle_api'
      ports:
        - "8080:8080"
      links :
        - mongo
    mongo:
      image : mongo
      ports:
        - "27017:27017"
    angular:
      build : './stackle_app'
      ports : 
        - "9000:9000"